# Nexus Artifacts Promotion Plugin
plugin.id=nexus-artifacts-promotion-plugin
plugin.version=${project.version}
plugin.name=Nexus Artifacts Promotion
plugin.description=Artifact promotion and remote repository sync plugin for Nexus 3.45.0
plugin.provider=NexusArtifactsPromotion
plugin.requires=Nexus 3.45.0
